name: 🚀 Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version semver
        required: true
        type: string
      tag:
        description: NPM tag
        required: false
        type: string
        default: 'latest'

jobs:
  from-template:
    uses: Unleash/.github/.github/workflows/npm-release.yml@v1.1.0
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.tag }}
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_TOKEN }}
